services:
  agent:
    build:
      context: ./agent
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ./agent:/app
      - ./common:/common
    tty: true
  server:
    build:
      context: ./server
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ./server:/app
      - ./common:/common
    tty: true