x-agent-base: &agent-base
  build:
    context: ./agent
    dockerfile: ./.devcontainer/Dockerfile
  volumes:
    - ./agent:/app
    - ./api:/api
  tty: true

x-server-base: &server-base
  build:
    context: ./server
    dockerfile: ./.devcontainer/Dockerfile
  volumes:
    - ./server:/app
    - ./api:/api
  tty: true

services:
  agent1:
    <<: *agent-base
    container_name: mqtt-agent1
    environment:
      - MQTT_CLIENT_ID=agent1
  # agent2:
  #   <<: *agent-base
  #   container_name: mqtt-agent2
  #   environment:
  #     - MQTT_CLIENT_ID=agent2
  # agent3:
  #   <<: *agent-base
  #   container_name: mqtt-agent3
  #   environment:
  #     - MQTT_CLIENT_ID=agent3

  server1:
    <<: *server-base
    container_name: mqtt-server1
    environment:
      - MQTT_CLIENT_ID=server1
