
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
    depends_on:
      - mosquitto
    tty: true
    container_name: tinylog-app
    environment:
      - MQTT_CLIENT_ID=server

  mosquitto:
    image: eclipse-mosquitto
    container_name: tinylog-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ../build/docker/mosquitto/:/mosquitto/


